### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by rdsilver** [comment]
:+1:

**Comment by dannyko** [comment]
i think i fixed it :) didn't merge because i wasn't sure what the second edit was for

**Comment by dannyko** [comment]
thanks!

**Comment by domoritz** [comment]
Github seems to automatically add an empty line to the end of each file.
It's a common practice but not necessary.

**Comment by dannyko** [comment]
i think that is something the text editor is doing and can be turned off in the settings, e.g. for sublime text see attached screenshot showing the appropriate option defining this behavior:

sublime_option1

**Comment by domoritz** [comment]
I didn't even use an editor and just edited the file online in Github.

**Comment by dannyko** [comment]
gotcha, guess their web editor has this feature. good to know :) cheers

**Pull request closed without merging**
